name: CodeCov Report
on: [push, pull_request]
jobs:
  run:
    runs-on: windows-latest
    name: Build, Test, Upload Code Coverage Report
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
        id: checkout_code
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.1
        id: setup_msbuild
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
      - name: Compile Google Test
        run: |
          qmake -r CONFIG+=test CONFIG+=console CONFIG+=c++11 UnitTest/UnitTest.pro
          make
      - name: Compile and Run Tests
        run: |
          g++ -o tests.exe main.cpp tst_getmpfromname.cpp -I$$GOOGLETEST_DIR/googletest/include -L. -lgtest
          ./tests.exe
      - name: Setup VSTest and add to PATH
        uses: darenm/Setup-VSTest@v1
        id: setup_vstest
      - name: Setup OpenCppCoverage and add to PATH
        id: setup_opencppcoverage
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $GITHUB_PATH
      - name: Generate Report
        id: generate_test_report
        shell: cmd
        run: OpenCppCoverage.exe -- "vstest.console.exe" UnitTest/tst_getmpfromname.dll
      - name: Set Environment Variables for Codecov
        run: echo "CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN1 }}" >> $GITHUB_ENV
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN1 }}
