name: Doxygen GitHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: path
        run: pwd
      - name: what-do-we-have-here
        run: ls
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: 'dconfig'


  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
          config_file: dconfig
