name: Windows Release

on:
  push:
    branches:
      - 'main'
      - 'hamzah'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'hamzah'

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.5.1
  ARTIFACT:     qt-mpGui-build.zip

jobs:
  build:
    runs-on:  windows-2019

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # ... Other steps ...

      - name: Install coverage package
        run: |
          pip install coverage

      - name: (8) Build and Generate Coverage Reports
        working-directory: ${{ runner.temp }}\build
        run: |
          qmake -r ${{ env.SOURCE_DIR }}\qtGuiApplication\cardTest.pro
          ${{ runner.temp }}\jom\jom -j2
          mkdir images
          copy ${{ env.SOURCE_DIR }}\images\* images
          cd release
          windeployqt --qmldir ${{ env.SOURCE_DIR }}\build\release cardTest.exe --pdb --release --compiler-runtime
          copy C:\Windows\System32\concrt140.dll . 
          copy C:\Windows\System32\vccorlib140.dll .
          copy C:\Windows\System32\msvcp140.dll .
          copy C:\Windows\System32\vcruntime140.dll .
        
          # Generate coverage reports
          coverage xml -o coverage.xml

      - name: (9) Zip build
        working-directory: ${{ runner.temp }}
        run:  |
          7z a qt-mpGui-build.zip ${{ runner.temp }}\build\* -r
              
      - name: (10) Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}\${{ env.ARTIFACT }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
